//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestRecord
    {
        public string Id { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<double> ED { get; set; }
        public Nullable<double> DER { get; set; }
        public string EventType { get; set; }
        public System.DateTime Time { get; set; }
        public string Operator { get; set; }
    }
}
